# Generated by Django 5.1.1 on 2024-10-05 13:02

from django.db import migrations, transaction


def create_default_institution(apps, schema_editor):
    Institution = apps.get_model('users', 'Institution')
    with transaction.atomic():
        Institution.objects.create(name='Default Institution', code='DEFAULT')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_institution'),
    ]

    operations = [
        migrations.RunPython(create_default_institution, reverse_code=migrations.RunPython.noop),
    ]
