# Generated by Django 5.1.1 on 2024-10-04 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0003_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.institution'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assessments', models.ManyToManyField(related_name='students', to='assessments.assessment')),
                ('courses', models.ManyToManyField(related_name='students', to='assessments.course')),
                ('playgrounds', models.ManyToManyField(related_name='students', to='assessments.playground')),
                ('quizzes', models.ManyToManyField(related_name='students', to='assessments.quiz')),
                ('teacher', models.ManyToManyField(related_name='students', to='users.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
