# Generated by Django 5.1.1 on 2024-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_identification_number_profile_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='identification_number',
        ),
        migrations.AddField(
            model_name='student',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users.student'),
        ),
    ]
