# Generated by Django 5.1.1 on 2024-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('users', '0006_alter_user_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assessments',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='assessments.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='playgrounds',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='assessments.playground'),
        ),
        migrations.AlterField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='assessments.quiz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='users.teacher'),
        ),
    ]
