# Generated by Django 5.1.1 on 2024-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_course_students_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='enrollment_code',
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
