# Generated by Django 5.1.1 on 2024-10-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playgrounds', to='users.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.student'),
        ),
    ]
