# Generated by Django 5.1.2 on 2024-10-09 09:19

import django.db.models.deletion
from django.db import migrations, models


def create_default_institution(apps, schema_editor):
    Institution = apps.get_model('users', 'Institution')
    if not Institution.objects.exists():
        Institution.objects.create(
            name="Default Institution",
            subscription_status="trial",
            # Add other required fields here
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_playground_student_alter_submission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.teacher'),
        ),
    ]
