# Generated by Django 5.1.2 on 2024-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
    ]
